print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "C:/Users/Kolleen/Chess/Assets/CHESSP~1/PAWNCH~4.MB"`)
{		
	file -o "C:/Users/Kolleen/Chess/Assets/CHESSP~1/PAWNCH~4.MB";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/Kolleen/Chess/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "C:/Users/Kolleen/Chess/Temp/CommandPipe";

$donepipeKill = `fopen "C:/Users/Kolleen/Chess/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
